#!/usr/bin/env python3
"""Extract candidate English UI literals from Kotlin into an Android catalogue.

This is deliberately a catalogue generator rather than a source rewriter: Kotlin
string resources need human review for plural forms, format arguments, and strings
that are protocol values rather than UI. It emits a reviewable values/strings.xml
fragment which can be merged into the app catalogue before translation.
"""

from __future__ import annotations

import argparse
import html
import hashlib
import re
from pathlib import Path

LITERAL = re.compile(r'(?<![A-Za-z0-9_])"((?:\\.|[^"\\])*)"')
SKIP_EXACT = {
    "true", "false", "null", "default", "none", "online", "offline", "idle", "dnd",
    "mobile", "desktop", "browser", "GET", "POST", "PUT", "DELETE",
}


def decode(value: str) -> str:
    return bytes(value, "utf-8").decode("unicode_escape") if "\\" in value else value


def candidate(value: str) -> bool:
    value = value.strip()
    if len(value) < 3 or "\n" in value or "${" in value or "\\" in value or any(ord(char) < 32 and char not in "\t" for char in value) or not re.search(r"[A-Za-zÀ-ž]", value):
        return False
    if value in SKIP_EXACT or value.startswith(("http://", "https://", "/", "--", "rgb", "rgba", "application/", "image/")):
        return False
    if re.fullmatch(r"[A-Za-z0-9_.:/-]+", value) or re.search(r"[%^$\\]", value):
        return False
    return True


def slug(value: str) -> str:
    words = re.findall(r"[A-Za-z0-9]+", value.lower())[:7]
    stem = "_".join(words) or "text"
    digest = hashlib.sha1(value.encode()).hexdigest()[:8]
    return f"catalog_{stem}_{digest}"


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--root", type=Path, default=Path("android/app/src/main/java"))
    parser.add_argument("--out", type=Path, default=Path("android/app/src/main/res/values/generated_catalog.xml"))
    args = parser.parse_args()

    values: dict[str, tuple[str, str]] = {}
    for source in sorted(args.root.rglob("*.kt")):
        text = source.read_text(encoding="utf-8", errors="ignore")
        for match in LITERAL.finditer(text):
            value = decode(match.group(1)).strip()
            if candidate(value):
                values.setdefault(slug(value), (value, str(source)))

    args.out.parent.mkdir(parents=True, exist_ok=True)
    lines = [
        '<?xml version="1.0" encoding="utf-8"?>',
        "<resources>",
        "    <!-- Generated by tools/extract_english_strings.py. Review protocol",
        "         values and plural sentences before translating. -->",
    ]
    for name, (value, source) in sorted(values.items()):
        # Quotes are legal in element text. Using numeric apostrophe entities
        # makes aapt interpret them as malformed unicode escapes in some AGP
        # versions, so escape only XML metacharacters that need it here.
        escaped = html.escape(value, quote=False).replace("'", "\\'").replace('"', '\\"')
        lines.append(f'    <string name="{name}" formatted="false">{escaped}</string>')
    lines.append("</resources>")
    args.out.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"wrote {len(values)} candidate strings to {args.out}")


if __name__ == "__main__":
    main()
