#!/usr/bin/env python3
"""Regenerate the emoji shortcode tables for web and Android.

Source: github/gemoji (MIT), the same alias set Discord/GitHub users already
know (`:sunflower:`, `:blush:`). Only the emoji that appear in the pickers'
`EMOJI_CATEGORIES` are emitted, so the table can't drift from what is offered.

    python3 tools/gen_emoji_shortcodes.py [path/to/gemoji.json]

Without an argument the db is fetched from GitHub.
"""

from __future__ import annotations

import json
import re
import sys
import urllib.request
from pathlib import Path

GEMOJI_URL = "https://raw.githubusercontent.com/github/gemoji/master/db/emoji.json"
ROOT = Path(__file__).resolve().parent.parent
WEB_SOURCE = ROOT / "packages/client/src/features/chat/emoji-data.ts"
WEB_OUT = ROOT / "packages/client/src/features/chat/emoji-shortcodes.ts"
ANDROID_OUT = (
    ROOT
    / "android/app/src/main/java/lt/oranges/orangchat/util/EmojiShortcodes.kt"
)

# Not in gemoji yet (Unicode 15.1 "head shaking" pair).
EXTRA = {
    "\U0001f642‍↔️": ("head_shaking_horizontally", "no shake head"),
    "\U0001f642‍↕️": ("head_shaking_vertically", "yes nod head"),
}


def variation_stripped(emoji: str) -> str:
    return emoji.replace("️", "")


def picker_emojis() -> list[str]:
    src = WEB_SOURCE.read_text(encoding="utf-8")
    blocks = re.findall(r"emojis: \[(.*?)\],\s*\}", src, re.S)
    seen: dict[str, None] = {}
    for block in blocks:
        for emoji in re.findall(r'"([^"]+)"', block):
            seen.setdefault(emoji, None)
    return list(seen)


def slug_from(words: list[str]) -> str:
    out = ""
    for word in words:
        nxt = f"{out}_{word}" if out else word
        if len(nxt) > 32:
            break
        out = nxt
    return out or "emoji"


def build_rows(db: list[dict]) -> list[tuple[str, list[str], list[str]]]:
    by_char = {}
    for entry in db:
        by_char.setdefault(variation_stripped(entry["emoji"]), entry)

    rows = []
    for emoji in picker_emojis():
        entry = by_char.get(variation_stripped(emoji))
        if entry:
            aliases = [a for a in entry["aliases"] if re.fullmatch(r"[a-z0-9_-]{2,32}", a)]
            words = re.findall(r"[a-z0-9]+", entry["description"].lower())
            # `:v:` and friends are shorter than the shortcode grammar allows,
            # and a few descriptions are longer - fall back to a trimmed slug.
            if not aliases:
                aliases = [slug_from(words)]
            keywords = sorted(
                {*entry.get("tags", []), *entry["aliases"], *words} - set(aliases),
            )
        elif emoji in EXTRA:
            alias, tags = EXTRA[emoji]
            aliases, keywords = [alias], tags.split()
        else:
            continue
        if aliases:
            rows.append((emoji, aliases, keywords))
    return rows


def pack(rows) -> str:
    return "\\n".join(
        f"{emoji}\\t{','.join(aliases)}\\t{' '.join(keywords)}" for emoji, aliases, keywords in rows
    )


def write_web(rows) -> None:
    WEB_OUT.write_text(
        "// Generated by tools/gen_emoji_shortcodes.py - do not edit.\n"
        "// Rows are `char\\taliases\\tkeywords`; parsed lazily by ./emoji-search.\n"
        f'export const EMOJI_TABLE =\n  "{pack(rows)}";\n',
        encoding="utf-8",
    )


def write_android(rows) -> None:
    # One literal per row: the whole table in a single string overruns what the
    # Kotlin lexer accepts.
    body = "\n".join(
        f'    "{emoji}\\t{",".join(aliases)}\\t{" ".join(keywords)}",'
        for emoji, aliases, keywords in rows
    )
    ANDROID_OUT.write_text(
        "package lt.oranges.orangchat.util\n\n"
        "// Generated by tools/gen_emoji_shortcodes.py - do not edit.\n"
        "// Rows are `char\\taliases\\tkeywords`; parsed lazily by EmojiSearch.\n"
        f"internal val EMOJI_TABLE: List<String> = listOf(\n{body}\n)\n",
        encoding="utf-8",
    )


def main() -> None:
    if len(sys.argv) > 1:
        db = json.loads(Path(sys.argv[1]).read_text(encoding="utf-8"))
    else:
        with urllib.request.urlopen(GEMOJI_URL, timeout=60) as response:
            db = json.load(response)

    rows = build_rows(db)
    write_web(rows)
    write_android(rows)
    print(f"{len(rows)} emoji, {sum(len(a) for _, a, _ in rows)} shortcodes")


if __name__ == "__main__":
    main()
