//! The game-presence registry, and the only place a detected game becomes text
//! other people can read.
//!
//! The registry is compiled into the binary from `packages/shared/games.json`
//! (generated by `scripts/build-game-registry.py`) so that the title and the
//! artwork url both come from data the server already trusts. A client sends an
//! id; it never sends a display name for a recognised game, and it can never
//! send an image url at all. That is the whole point of the split: presence text
//! is broadcast to everyone who can see the user, so a client that could choose
//! it freely would be an open broadcast channel with someone else's name on it.
//!
//! The escape hatch for an unrecognised process - a game the registry has never
//! heard of, allowed by hand in the desktop client's settings - comes through as
//! a custom name, which is sanitized here and rendered without artwork.

use std::collections::HashMap;
use std::sync::OnceLock;

use chrono::Utc;
use serde::Deserialize;

use crate::dto::ActivityDto;
use crate::error::AppResult;
use crate::services::presence;
use crate::state::AppState;
use crate::timefmt::iso;

/// Enough of a registry entry to answer "what is this id called". The rest of
/// the file - the executable names - is detection-side data the client needs
/// and the server has no use for.
#[derive(Debug, Deserialize)]
struct RegistryEntry {
    id: String,
    name: String,
}

#[derive(Debug, Deserialize)]
struct Registry {
    games: Vec<RegistryEntry>,
}

const REGISTRY_JSON: &str = include_str!("../../../shared/games.json");

/// A hand-allowed name is a label, not prose. Long enough for the longest real
/// titles, short enough that it cannot be used to shout in a member list.
const MAX_CUSTOM_NAME: usize = 64;

fn registry() -> &'static HashMap<String, String> {
    static REGISTRY: OnceLock<HashMap<String, String>> = OnceLock::new();
    REGISTRY.get_or_init(|| {
        let parsed: Registry = serde_json::from_str(REGISTRY_JSON)
            .expect("games.json is generated and compiled in; a parse failure is a build error");
        parsed
            .games
            .into_iter()
            .map(|entry| (entry.id, entry.name))
            .collect()
    })
}

/// Strip a hand-entered name down to something safe to render inline.
///
/// Control characters and the bidi overrides are the ones that matter: the
/// former can break a line out of its own row, and the latter can make a name
/// render as text it does not contain. Everything else - emoji, non-Latin
/// scripts - is a legitimate game title somewhere.
fn sanitize_custom(name: &str) -> Option<String> {
    let cleaned: String = name
        .chars()
        .filter(|c| !c.is_control() && !('\u{202a}'..='\u{202e}').contains(c) && *c != '\u{2066}')
        .collect();
    let trimmed = cleaned.trim();
    if trimmed.is_empty() {
        return None;
    }
    Some(trimmed.chars().take(MAX_CUSTOM_NAME).collect())
}

/// The artwork for a registry id, served from our own origin.
///
/// Every registry entry has a tile (`fetch-game-art.py` falls back to a
/// generated monogram rather than leaving one out), so this never needs to
/// answer "no art". Re-hosting instead of linking Valve's cdn is deliberate:
/// an `<img>` pointing at a third party would put the ip of everyone who can
/// see the presence line in front of that third party.
fn image_url(id: &str) -> String {
    format!("/games/{id}.webp")
}

/// Resolve what the client reported into the activity everyone else will see.
///
/// `started_at` is carried over from the activity already being broadcast when
/// it is for the same game, so the elapsed timer survives reconnects, other
/// tabs, and the desktop client's own polling interval.
pub fn resolve(
    game_id: Option<&str>,
    custom_name: Option<&str>,
    previous: Option<&ActivityDto>,
    now: String,
) -> Option<ActivityDto> {
    let (name, image_url) = match (game_id, custom_name) {
        (Some(id), _) => {
            let name = registry().get(id)?.clone();
            (name, Some(image_url(id)))
        }
        (None, Some(custom)) => (sanitize_custom(custom)?, None),
        (None, None) => return None,
    };

    // Same title as a moment ago means the same session; anything else is a new
    // one and starts its clock now.
    let started_at = previous
        .filter(|activity| activity.name == name)
        .and_then(|activity| activity.started_at.clone())
        .or(Some(now));

    Some(ActivityDto {
        kind: "game".into(),
        name,
        details: None,
        url: None,
        image_url,
        started_at,
        ends_at: None,
    })
}

/// Whether this account has "Display the game you're playing" on.
///
/// Re-read on every report rather than cached on the socket: the setting is
/// changed from a different tab or a different device entirely, and the point of
/// switching it off is that presence stops immediately.
async fn is_enabled(state: &AppState, user_id: &str) -> bool {
    sqlx::query_scalar::<_, bool>(r#"SELECT "gameActivity" FROM "User" WHERE id = $1"#)
        .bind(user_id)
        .fetch_optional(&state.pool)
        .await
        .ok()
        .flatten()
        .unwrap_or(false)
}

/// Apply a client's report. Returns true when presence needs re-broadcasting.
///
/// A report that resolves to nothing - an id the registry does not know, a
/// custom name that sanitizes away, or the setting being off - clears the
/// activity rather than being ignored, so a client can never pin a stale game to
/// a profile by following a good report with a bad one.
pub async fn report(
    state: &AppState,
    user_id: &str,
    game_id: Option<&str>,
    custom_name: Option<&str>,
) -> AppResult<bool> {
    let activity = if is_enabled(state, user_id).await {
        let activities = presence::get_activities(state, user_id).await?;
        let previous = activities.iter().find(|item| item.kind == "game");
        resolve(game_id, custom_name, previous, iso(Utc::now().naive_utc()))
    } else {
        None
    };
    presence::set_activity(state, user_id, "game", activity).await
}

/// Drop whatever game the user was reported as playing.
///
/// Presence itself survives one device going away - the web client keeps the
/// user online - but the game does not: only the desktop shell can see the
/// process list, so once it is gone nobody is left to notice the game stopped.
pub async fn clear(state: &AppState, user_id: &str) -> AppResult<bool> {
    presence::set_activity(state, user_id, "game", None).await
}

#[cfg(test)]
mod tests {
    use super::*;

    fn dto(name: &str, started_at: &str) -> ActivityDto {
        ActivityDto {
            kind: "game".into(),
            name: name.into(),
            details: None,
            url: None,
            image_url: None,
            started_at: Some(started_at.into()),
            ends_at: None,
        }
    }

    #[test]
    fn registry_parses_and_is_populated() {
        // A generator regression that empties the file would otherwise show up
        // as "detection silently stopped working" in production.
        assert!(registry().len() > 1000);
    }

    #[test]
    fn unknown_id_resolves_to_nothing() {
        assert!(resolve(Some("not-a-real-game"), None, None, "t0".into()).is_none());
    }

    #[test]
    fn known_id_takes_its_name_and_art_from_the_registry() {
        let id = registry().keys().next().unwrap().clone();
        let resolved = resolve(Some(&id), None, None, "t0".into()).unwrap();
        assert_eq!(resolved.name, registry()[&id]);
        assert_eq!(resolved.image_url, Some(format!("/games/{id}.webp")));
    }

    #[test]
    fn custom_name_never_gets_artwork() {
        let resolved = resolve(None, Some("Some Indie Game"), None, "t0".into()).unwrap();
        assert_eq!(resolved.name, "Some Indie Game");
        assert_eq!(resolved.image_url, None);
    }

    #[test]
    fn custom_name_is_stripped_and_capped() {
        assert!(resolve(None, Some("  \u{202e}\n "), None, "t0".into()).is_none());
        let long = "x".repeat(200);
        let resolved = resolve(None, Some(&long), None, "t0".into()).unwrap();
        assert_eq!(resolved.name.chars().count(), MAX_CUSTOM_NAME);
    }

    #[test]
    fn elapsed_clock_survives_a_repeat_report() {
        let previous = dto("Held Over", "t0");
        let resolved = resolve(None, Some("Held Over"), Some(&previous), "t9".into()).unwrap();
        assert_eq!(resolved.started_at, Some("t0".into()));
    }

    #[test]
    fn a_different_game_restarts_the_clock() {
        let previous = dto("Something Else", "t0");
        let resolved = resolve(None, Some("Held Over"), Some(&previous), "t9".into()).unwrap();
        assert_eq!(resolved.started_at, Some("t9".into()));
    }
}
