-- Media preview metadata: generated by the sender's client at upload time so
-- every receiver can show a preview without downloading the file.
-- * duration   - seconds, for audio and video.
-- * thumbnailUrl - a still (first frame) image for video.
ALTER TABLE "PendingAttachment"
    ADD COLUMN IF NOT EXISTS "duration" DOUBLE PRECISION,
    ADD COLUMN IF NOT EXISTS "thumbnailUrl" TEXT;
